name: spynner
channels:
  - conda-forge
dependencies:
  - python
  - ipython
  - jupyter
  - pillow
  - numpy
  - matplotlib
  - pyside
  - six
  - scikit-learn
  - pip:
    - https://github.com/tjwei/spynner/archive/master.zip


